# Generated by Django 4.1.5 on 2023-01-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('impressions', models.IntegerField(max_length=100)),
                ('clicks', models.IntegerField()),
                ('installs', models.IntegerField()),
                ('spend', models.FloatField()),
                ('revenue', models.FloatField()),
            ],
            options={
                'verbose_name': 'metric',
                'verbose_name_plural': 'metrics',
            },
        ),
    ]
