# Generated by Django 4.1.5 on 2023-01-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsys', '0002_rename_date_metric_transaction_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='metric',
            new_name='File',
        ),
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
    ]
